### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security sledi fiksnemu pravilniku o 탑ivljenjskem ciklu.
  ms.date: 08/28/2020
name: Microsoft Forefront Client Security
summary: |+
  Microsoft Forefront Client Security sledi [fiksnemu](/lifecycle/policies/fixed) pravilniku o 탑ivljenjskem ciklu.


products:
  - msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
  - version: Original Release
    startDate: 08/02/2007
    endDate: 07/14/2015
content: |+

  ## <a name="links"></a>Povezave 
  * [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)

  > [!NOTE]
  > Forefront Client Security je bil ukinjen 14. julija 2015. Posodobitve definicij protivirusnih in protivohunskih programov po koncu podpore za razli훾ico izdelka ne bodo ve훾 na voljo. Ocenite, ali bi jih zamenjali s programom System Center Endpoint Protection.