### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security upošteva določen pravilnik življenjskega cikla.
  ms.date: 08/21/2020
  ms.openlocfilehash: 802c6836324ac39b0b8ffc99c1f7f6734906445b
  ms.sourcegitcommit: 2f3e18a9447115504ef274bd044dbcdb08231f5b
  ms.translationtype: MT
  ms.contentlocale: sl-SI
  ms.lasthandoff: 08/25/2020
  ms.locfileid: "908910"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security upošteva [določen](/lifecycle/policies/fixed) pravilnik življenjskega cikla.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Povezave \n* [Zaščita končne točke središča sistema](http://www.microsoft.com/server-cloud/products/system-center-2012-r2-configuration-manager/default.aspx)\n\n> [!NOTE]\n> Vnaprejšnja varnost odjemalca je bila prekinjena. Podpora se konča julij 14, 2015. Posodobitve za antimalware in protivohunsko definicijo ne bodo več na voljo za konec podpore za različico izdelka. Prosimo, da ocenite zaščito končne točke sistemskega središča kot zamenjavo."
