### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: Microsoft Forefront Client Security upošteva določen pravilnik življenjskega cikla.
  ms.date: 08/28/2020
  ms.openlocfilehash: 335ae81ffa4b7cb64352b19e7330765a4cac6c68
  ms.sourcegitcommit: 570c824dbe19150d37398333df7d2c416a51eac9
  ms.translationtype: MT
  ms.contentlocale: sl-SI
  ms.lasthandoff: 08/28/2020
  ms.locfileid: "924272"
name: Microsoft Forefront Client Security
summary: >+
  Microsoft Forefront Client Security upošteva [določen](/lifecycle/policies/fixed) pravilnik življenjskega cikla.


products:
- msc
policyType: fixed
supportDates:
  start: 08/02/2007
  extendedEnd: 07/14/2015
releases:
- version: Original Release
  startDate: 08/02/2007
  endDate: 07/14/2015
content: "\n## <a name=\"links\"></a>Povezave \n* [Zaščita končne točke središča sistema](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> Forefront Client Security je bila prekinjena od julija 14, 2015. Posodobitve za antimalware in protivohunsko definicijo ne bodo več na voljo za konec podpore za različico izdelka. Prosimo, da ocenite zaščito končne točke sistemskega središča kot zamenjavo."
