### YamlMime:Lifecycle
metadata:
  title: Upravitelj konfiguracije Microsoft System Center 2012 R2
  description: Upravitelj konfiguracije za Microsoft System Center 2012 R2 sledi pravilniku o fiksnem življenjskem ciklu.
  ms.date: 03/12/2021
  keywords: 
  ms.openlocfilehash: 9e7bbf1db9f64b796da4e0c31bf66ce1b7dea0367121fbaeb1f2f41e60a20772
  ms.sourcegitcommit: 1c28c95e7a2b743cff45216da63f72ffbad026ed
  ms.translationtype: HT
  ms.contentlocale: sl-SI
  ms.lasthandoff: 08/06/2021
  ms.locfileid: "2523689"
name: Upravitelj konfiguracije Microsoft System Center 2012 R2
summary: >+
  Upravitelj konfiguracije za Microsoft System Center 2012 R2 sledi pravilniku o [fiksnem](/lifecycle/policies/fixed) življenjskem ciklu.


products:
- msc
policyType: fixed
supportDates:
  start: 01/16/2014
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 1
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Original Release
  startDate: 01/16/2014
  endDate: 07/12/2016
content: "\n## <a name=\"links\"></a>Povezave \n* [Pravilnik servisnih paketov](/lifecycle/policies/fixed#service-packs)\n* [Dokumentacija za upravitelja konfiguracije](/mem/configmgr/core/misc/online-documentation)\n* [Navodila za učinkovito selitev](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)"
