### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.6
  description: Microsoft Application Virtualization 4.6 sledi fiksnemu pravilniku o življenjskem ciklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: 868274b4468e663afe8e1b9f36069490ab4da025
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: sl-SI
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "839658"
name: Microsoft Application Virtualization 4.6
summary: >+
  Microsoft Application Virtualization 4.6 sledi [fiksnemu](/lifecycle/policies/fixed) pravilniku o življenjskem ciklu.


  To velja za naslednje izdaje: za storitve oddaljenega namizja, za namizja sistema Windows, Sequencer

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Povezave \n* [Informacije o izdelku in selitvi](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Navodila za učinkovito selitev](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [Pravilnik servisnih paketov](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Ker odjemalec App-V 4.6 uporablja strežnik App-V 4.5, bo strežnik App-V 4.5 še naprej podprt glede na datume življenjskega cikla aplikacije V 4.6, kadar je v uporabi s podprtim odjemalcem App-V 4.6.\n\n## <a name=\"editions\"></a>Izdaje \n* za storitve oddaljenega namizja\n* za namizja sistema Windows\n* Sequencer"
