### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 sledi fiksnemu pravilniku o 탑ivljenjskem ciklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: cffcc1c2bb51fc5023fe6ad29d62132141ffedb2
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: HT
  ms.contentlocale: sl-SI
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "863257"
name: Microsoft System Center Configuration Manager 2007 R3
summary: >
  Microsoft System Center Configuration Manager 2007 R3 sledi [fiksnemu](/lifecycle/policies/fixed) pravilniku o 탑ivljenjskem ciklu.



  > [!IMPORTANT]

  > Podpora za ta izdelek je kon훾ana. Preberite spodnje smernice za selitev.
products:
- msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
- version: Original Release
  startDate: 12/19/2010
  endDate: 07/09/2019
content: "\n## <a name=\"links\"></a>Povezave \n* [Navodila za u훾inkovito selitev](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Dodatne smernice za selitev](/mem/configmgr/core/migration/planning-for-migration)"
