### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.5 za namizne računalnike Windows
  description: Microsoft Application Virtualization Hosting 4.5 za namizja sistema Windows sledi fiksnemu pravilniku o življenjskem ciklu.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 4.5 za namizne računalnike Windows
summary: |
  Microsoft Application Virtualization Hosting 4.5 za namizja sistema Windows sledi [fiksnemu](/lifecycle/policies/fixed) pravilniku o življenjskem ciklu.

  To velja za naslednje izdaje: za namizja sistema Windows

  > [!IMPORTANT]
  > Podpora za ta izdelek je končana. Glejte informacije o selitvi spodaj.
products:
  - windows
policyType: fixed
supportDates:
  start: 11/23/2008
  end: 01/14/2014
  extendedEnd: 01/08/2019
releases:
  - version: Service Pack 2
    startDate: 08/15/2010
    endDate: 01/08/2019
  - version: Service Pack 1
    startDate: 12/13/2009
    endDate: 10/11/2011
  - version: Original Release
    startDate: 11/23/2008
    endDate: 01/11/2011
content: |

  ## <a name="links"></a>Povezave 
  * [Informacije o izdelku in selitvi](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Pravilnik servisnih paketov](/lifecycle/policies/fixed#service-packs)


  ## <a name="editions"></a>Izdaje 
  * za namizja sistema Windows