### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
  description: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops sledi fiksnemu pravilniku o življenjskem ciklu.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 8a32729ae5fbf7f57a14b6a6ec048c7a1f412a52
  ms.sourcegitcommit: af46dd09ccdabd80dcc49d2cd930cefa0b1ab8a6
  ms.translationtype: HT
  ms.contentlocale: sl-SI
  ms.lasthandoff: 09/01/2020
  ms.locfileid: "935466"
name: Microsoft Application Virtualization Hosting 4.6 for Windows Desktops
summary: >+
  Microsoft Application Virtualization Hosting 4.6 for Windows Desktops sledi [fiksnemu](/lifecycle/policies/fixed) pravilniku o življenjskem ciklu.


  To velja za naslednje izdaje: for Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Povezave \n* [Informacije o izdelku in selitvi](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Pravilnik servisnih paketov](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Ker odjemalec App-V 4.6 uporablja strežnik App-V 4.5, bo strežnik App-V 4.5 še naprej podprt glede na datume življenjskega cikla aplikacije V 4.6, kadar je v uporabi s podprtim odjemalcem App-V 4.6.\n\n## <a name=\"editions\"></a>Izdaje \n* for Windows Desktops"
