### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 za namizja sistema Windows
  description: Microsoft Application Virtualization Hosting 4.6 za namizja sistema Windows sledi pravilniku o fiksnem življenjskem ciklu.
  ms.date: 07/28/2020
  ms.openlocfilehash: 21ed557cd6333e43a274796a3b25791c0d7f96cd
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: sl-SI
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "839652"
name: Microsoft Application Virtualization Hosting 4.6 za namizja sistema Windows
summary: >+
  Microsoft Application Virtualization Hosting 4.6 za namizja sistema Windows sledi pravilniku o [fiksnem](/lifecycle/policies/fixed) življenjskem ciklu.


  To velja za te izdaje: za namizja sistema Windows

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Povezave \n* [Informacije o izdelku in selitvi](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Pravilnik o servisnem paketu](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Ker odjemalec App-V 4.6 uporablja strežnik App-V 4.5, bo strežnik App-V 4.5 še naprej podprt glede na datume življenjskega cikla aplikacije V 4.6, ko je v uporabi s podprtim odjemalcem App-V 4.6.\n\n## <a name=\"editions\"></a>Izdajah \n* za namizja sistema Windows"
