### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager (LTSB - različica 1606)
  description: Microsoft System Center Configuration Manage (LTSB - različica 1606) sledi fiksnemu pravilniku o življenjskem ciklu.
  ms.date: 08/20/2020
  ms.openlocfilehash: c918fa35a50ffac8ee9d31cb0b704aac444cefe1
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: sl-SI
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4106210"
name: Microsoft System Center Configuration Manager (LTSB - različica 1606)
summary: >+
  Microsoft System Center Configuration Manage (LTSB - različica 1606) sledi [fiksnemu](/lifecycle/policies/fixed) pravilniku o življenjskem ciklu.


products:
- m365
policyType: fixed
supportDates:
  start: 2016-10-12T00:00:00.000-08:00
  end: 2021-10-12T22:59:59.999-08:00
  extendedEnd: 2027-01-12T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2016-10-12T00:00:00.000-08:00
  endDate: 2027-01-12T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Povezave \n* [Informacije o servisiranju in podpori](/sccm/core/understand/learn-more-editions)"
