### YamlMime:Lifecycle
metadata:
  title: Inteligentni prehod aplikacije Kit za komunikacijo
  description: Pravilnik o nespremenljivem življenjskem ciklu za komunikacijo kitov
  ms.date: 08/21/2020
  ms.openlocfilehash: 4946cfbd0c53706853138bd707157a5c318b8dc6
  ms.sourcegitcommit: bc7fcda30191f92db77ed2e7f74d5816ac276a55
  ms.translationtype: MT
  ms.contentlocale: sl-SI
  ms.lasthandoff: 08/21/2020
  ms.locfileid: "907157"
name: Inteligentni prehod aplikacije Kit za komunikacijo
summary: >+
  Pravilnik o [nespremenljivem](/lifecycle/policies/fixed) življenjskem ciklu za komunikacijo kitov


products:
- windows
policyType: fixed-mainstream-only
supportDates:
  start: 10/10/2007
  end: 07/13/2010
releases:
- version: "3.1"
  startDate: 10/10/2007
  endDate: 07/08/2008
- version: "3.6"
  startDate: 10/10/2007
  endDate: 07/13/2010
content: "\n\n> [!NOTE]\n> Podpora za ta izdelek je na voljo na podlagi pogojev njegovega nakupa."
